FROM node as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN ls -l
ARG REACT_APP_NAME
ENV REACT_APP_NAME=${REACT_APP_NAME}
EXPOSE 8080
CMD ["npm", "run", "build"]

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html