name: Github pages deploy

  # The image to use for the build.
  image: docker:stable
 
  # The stages of the workflow.
  stages:
    - build
    - deploy
 
  # The on-conditions of the workflow.
  on:
    push:
      branches:
        - 'main'

  # The jobs of the workflow.
  jobs:
    build-container:
      name: Build Container
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
        - uses: actions/checkout@v3

        name: Build and push Docker images
        uses: actions/docker@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: edithbdev/react-app

        - name: Deploy to GitHub Pages
        - uses: actions/github-pages-deploy@v1
          with:
            repository: edithbdev/react-app
            branch: main
            ssh-key: ${{ secrets.REACT_PROJECT_DEPLOY_KEY }}
            message: "Deployed to GitHub Pages"
              

       